### ISSUE TITLE
On Anytone 868 and 878, setting a receive tone does not enable tone squelch

### ISSUE THREAD

**Issue by jdsteele** [sergev/dmrconfig#34]
On analog channels, setting a CTCSS or DCS value does not also set squelch_mode to SQ_TONE.

**Comment by sergev** [comment]
Frankly, I'm not sure this is a bug. SQ_TONE mode means you don't want to hear others on this repeater who have a different CTCSS or DCS setting. This seems pretty infrequent situation: a crowded frequency with multiple tones. Dmrconfig sets a SQ_CARRIER mode instead, which means you are going to hear everybody on this frequency.

**Comment by jdsteele** [comment]
Well, sure. If I want to hear everybody, I set the RxTone column to "-" which implies squelch_mode will be SQ_CARRIER. But if I set RxTone to "100.0", I would expect to only hear radios transmitting with a CTCSS of 100.0. On these models, that requires squelch_mode to be SQ_TONE.

**Comment by jdsteele** [comment]
Fixed in #35

**Comment by sergev** [comment]
OK, I agree. I still don't understand why we need a separate squelch_mode bit, as we already have separate ctcss_receive and dcs_receive bits. But anyway, you are right. I'll merge your pull request #35. Thank you for the patch.

**Comment by jdsteele** [comment]
No problem. Glad I could help.

The on-radio menu for Squelch Mode, which presumably has a direct relationship to ch->squelch_mode, actually has 5 entries. The documentation is vague, but it appears the other 3 entries are related to 2 Tone / 5 Tone signaling. I guess I can update the SQ_ constants, for clarity, once I verify the values.
